name: ParaTech
favicon: null
layout_spectrum: 0.749650742392987
typography_spectrum: 0.04635739256627858
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7182704689912498
  lightness: 0.6123033745680004
  saturation: 0.08910475578159094
  rhythmicContrast: 0.2232061680406332
purpose: []
